<?php

namespace controllers;

use bundle\Controller;
use bundle\Redirector;
use bundle\Session;
use bundle\View;
use models\User;

class SettingsController extends Controller
{
    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    public function doIndex()
    {
        return View::render('settings/index.php');
    }

    public function doAddSettings()
    {
        $request = $this->request->data();
        $user    = Session::get('user');

        User::update(['settings' => json_encode($request)], $user['id']);

        Redirector::to('/game');
        return true;
    }
}